# Generated by Django 5.2.7 on 2025-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
