# Generated by Django 5.2.7 on 2025-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
