# Generated by Django 5.2.7 on 2025-11-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_address_order_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
