# Generated by Django 5.2.7 on 2025-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0014_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
