# Generated by Django 5.2.7 on 2025-11-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='Product',
        ),
    ]
